AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Event-driven Python. Performs ETL job on two Covid-19 data sources to combine into single dashboard 

Globals:
  #https://github.com/awslabs/serverless-application-model/blob/develop/docs/globals.rst
  Function:
    Runtime: python3.8
    Timeout: 120
    Environment:
      Variables:
        table: !Ref dataNYTcovid

Resources:
  etlFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref dataNYTcovid
      Events:
        Schedule2:
          Type: Schedule
          Properties:
            Schedule: cron(0 16 * * ? *)

  dataNYTcovid:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions: 
        - AttributeName: Date
          AttributeType: S
      KeySchema: 
        - AttributeName: Date
          KeyType: HASH
      ProvisionedThroughput: #in free tier limits
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
    
  

  
    