AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Event-driven Python. Performs ETL job on two Covid-19 data sources to combine into single dashboard 

Globals:
  #https://github.com/awslabs/serverless-application-model/blob/develop/docs/globals.rst
  Function:
    Runtime: python3.8
    Timeout: 20
    Environment:
      Variables:
        table: !Ref CovidData
        bucket: !Ref CovidDataStorage

Parameters:
  ArtifactsBucket:
    Type: String

Resources:
  etlFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      MemorySize: 256
      CodeUri: ./
      Handler: extract.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CovidData
        - S3CrudPolicy:
            BucketName: !Ref CovidDataStorage
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: cron(0 16 * * ? *)

  CovidTotalsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      MemorySize: 192
      CodeUri: ./
      Handler: totals.lambda_handler
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref CovidDataStorage
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /
            Method: GET
            RestApiId: 
              Ref: CovidTotalsApi

  CovidTotalsApi:
    Type: AWS::Serverless::Api
    Properties:
      EndpointConfiguration: Regional
      StageName: prod
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: s3://logantoler/totals-openapi.yaml
      OpenApiVersion: 3.0.1

  CovidData:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions: 
        - AttributeName: Date
          AttributeType: S
      KeySchema: 
        - AttributeName: Date
          KeyType: HASH
      ProvisionedThroughput: #in free tier limits
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  CovidDataStorage:
    Type: AWS::S3::Bucket
    Properties:
      Tags:
        - Key: "etlFunction"
          Value: "CovidDataStorage"
    