name: CovidETL CI/CD

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install and upgrade Pip
        run: python -m pip install --upgrade pip

      - name: config aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Building and Packaging SAM Application
        run: sam build -u && sam package --s3-bucket ${{ secrets.AWS_S3_SAM_BUCKET }} --region ${{ secrets.AWS_REGION }}

      - name: Deploying SAM Application to CloudFormation Stack 
        run: sam deploy --template-file .aws-sam/build/template.yaml --stack-name ${{ secrets.AWS_STACK_NAME }} --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM --region ${{ secrets.AWS_REGION }} --no-fail-on-empty-changeset --force-upload